// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQtVFW7jmYsgkPG5ymLyNda-TrbJHE3Hc',
    appId: '1:418990663135:web:0a3dececc7e628c04dd06a',
    messagingSenderId: '418990663135',
    projectId: 'g7-mae-assignment-bcc3e',
    authDomain: 'g7-mae-assignment-bcc3e.firebaseapp.com',
    storageBucket: 'g7-mae-assignment-bcc3e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCSyiWtDWOKY37bMcve6XBL-49PXBwkoI',
    appId: '1:418990663135:android:4c275b19d49c2c754dd06a',
    messagingSenderId: '418990663135',
    projectId: 'g7-mae-assignment-bcc3e',
    storageBucket: 'g7-mae-assignment-bcc3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtFVCI-ic0imHmSrW7t__WZ0GnHDxQ8DU',
    appId: '1:418990663135:ios:9c1f41c303a234314dd06a',
    messagingSenderId: '418990663135',
    projectId: 'g7-mae-assignment-bcc3e',
    storageBucket: 'g7-mae-assignment-bcc3e.firebasestorage.app',
    iosBundleId: 'com.example.grpMaeAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtFVCI-ic0imHmSrW7t__WZ0GnHDxQ8DU',
    appId: '1:418990663135:ios:9c1f41c303a234314dd06a',
    messagingSenderId: '418990663135',
    projectId: 'g7-mae-assignment-bcc3e',
    storageBucket: 'g7-mae-assignment-bcc3e.firebasestorage.app',
    iosBundleId: 'com.example.grpMaeAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQtVFW7jmYsgkPG5ymLyNda-TrbJHE3Hc',
    appId: '1:418990663135:web:a771664d69fc3dcf4dd06a',
    messagingSenderId: '418990663135',
    projectId: 'g7-mae-assignment-bcc3e',
    authDomain: 'g7-mae-assignment-bcc3e.firebaseapp.com',
    storageBucket: 'g7-mae-assignment-bcc3e.firebasestorage.app',
  );
}
